// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetReleaseInfo(arg1) {
  return window['go']['main']['App']['GetReleaseInfo'](arg1);
}

export function GetRequest(arg1) {
  return window['go']['main']['App']['GetRequest'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function PatchRequest(arg1, arg2) {
  return window['go']['main']['App']['PatchRequest'](arg1, arg2);
}

export function RefreshCurrentUser() {
  return window['go']['main']['App']['RefreshCurrentUser']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartAuthProcess() {
  return window['go']['main']['App']['StartAuthProcess']();
}
