// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRequest(arg1:string):Promise<string>;

export function PatchRequest(arg1:string,arg2:string):Promise<string>;

export function StartAuthProcess():Promise<void>;
