// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRequest(arg1) {
  return window['go']['main']['App']['GetRequest'](arg1);
}

export function PatchRequest(arg1, arg2) {
  return window['go']['main']['App']['PatchRequest'](arg1, arg2);
}

export function StartAuthProcess() {
  return window['go']['main']['App']['StartAuthProcess']();
}
